project:
  type: website
  output-dir: _site

website:
  title: "Colt Holley"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research"
      - href: cv.qmd
        text: "CV"
    tools:
      - icon: github
        href: https://github.com/ctholley/colt-website

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
