name: Deploy Quarto Website

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    concurrency:
      group: deploy-quarto

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Get latest Quarto version
        id: get_version
        run: |
          latest=$(curl -s https://api.github.com/repos/quarto-dev/quarto-cli/releases/latest | jq -r .tag_name)
          echo "version=${latest#v}" >> $GITHUB_OUTPUT

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: ${{ steps.get_version.outputs.version }}

      - name: Render Quarto Project
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages